# Generated by Django 5.0.3 on 2024-03-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='accountNumber',
            new_name='accountNo',
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='image1',
            new_name='chequeImg',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='image2',
        ),
    ]
