# Generated by Django 5.0.6 on 2024-08-15 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_accountnumber_cheque_accountno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='croppedImg',
            field=models.ImageField(blank=True, null=True, upload_to='cropped_signatures/'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='forgery_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='verification_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
