# Generated by Django 5.0.6 on 2024-08-19 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_cheque_croppedimg_cheque_forgery_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
