# Generated by Django 5.0.6 on 2024-07-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signImg',
            field=models.ImageField(default='', upload_to='user_signatures/'),
            preserve_default=False,
        ),
    ]
