# Generated by Django 5.0.6 on 2024-07-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address_alter_user_signimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signImg',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/'),
        ),
    ]
