# Generated by Django 5.0.6 on 2024-07-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_signimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenshipImg',
            field=models.ImageField(blank=True, null=True, upload_to='citizenships/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
