# Generated by Django 5.0.6 on 2024-07-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_citizenshipimg_alter_user_email'),
    ]

    operations = [
    ]
