# Generated by Django 5.0.6 on 2024-08-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
